# Generated by Django 6.0 on 2026-03-16 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=0, help_text='Минимальный остаток. 0 = без ограничений'),
        ),
        migrations.AddField(
            model_name='part',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Зарезервировано под заявки'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('status', 'Смена статуса'), ('assign', 'Назначение мастера'), ('new', 'Новая заявка'), ('stock', 'Склад'), ('part', 'Запчасти'), ('work', 'Работы'), ('other', 'Прочее')], default='other', max_length=20)),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repair_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='service.repairrequest')),
                ('target_user', models.ForeignKey(blank=True, help_text='Кому адресовано. NULL = системное событие (видят менеджеры)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('released', models.BooleanField(default=False)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='service.part')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='service.repairrequest')),
                ('reserved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
